backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

media_folder: "static/images"   # Media files will be stored in the repo under static/images
public_folder: "/images"        # The src attribute for uploaded media will begin with /images

collections:
  - name: 'projects'       # Used in routes, e.g., /admin/collections/project
    label: 'Projects'      # Used in the UI
    label_singular: 'Project'
    folder: 'content/projects'
    format: 'frontmatter'
    create: true           # Allow users to create new documents in this collection
    slug: '{{slug}}'       # Filename template
    editor:
      preview: false
    fields:     # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Short Description', name: 'short_description', widget: 'string', required: true }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: true, allow_multiple: false }
